name: 'Test WordPress Coding Standards'
description: 'Test WordPress Coding Standards, PHP Coding Standard and PHPCompatibility'
inputs:
  php: # id of input
    description: 'PHP Version to be checked compatibility with'
    default: '7.2'
  text-domain: # id of input
    description: 'Text domain of the project'
outputs:
  php: # id of output
    description: 'PHP Version that checked compatibility with'
runs:
  using: 'composite'
  steps:
    - run: scripts/test.sh
      shell: bash