name: Test WordPress Coding Standards
description: 'Test WordPress Coding Standards, PHP Coding Standard and PHPCompatibility'
inputs:
  php:
    description: PHP Version to be checked compatibility with
    default: '7.2'
  text-domain:
    description: Text domain of the project
outputs:
  php:
    description: PHP Version that checked compatibility with
runs:
  using: composite
  steps:
    - run: wpcs.sh
      shell: bash
