name: 'Test WordPress Coding Standards'

description: 'Test WordPress Coding Standards, PHP Coding Standard and PHPCompatibility.'
author: 'imjafran'

inputs:

  php:
    description: 'PHP Version to be checked compatibility with.'
    default: '8.2'

  text-domain:
    description: 'Text domain of the project'
    default: ''

  phpcs:
    description: 'Coding Standard from an external public URL.'
    default: 'https://raw.githubusercontent.com/imjafran/wpcs/master/data/phpcs.xml'

  wpscan:
    description: 'Use WPScan to detect vulnerability.'
    default: false

outputs:
  php:
    description: 'PHP Version that checked compatibility with.'
    value: ${{ steps.test.outputs.report }}

runs:
  using: 'composite'
  steps:
    - id: test
    - run: ${{ github.action_path }}/script.sh
      shell: bash
