name: Basic WPCS Check

on: [push, pull_request]

jobs:
  wpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: phpwpcs Check
        # For production: uses: imjafran/phpwpcs@v1.0.0
        # For development: uses: ./
        uses: imjafran/phpwpcs@v1.0.0