name: WordPress Theme Check

on: 
  push:
    paths: ['**.php']
  pull_request:
    paths: ['**.php']

jobs:
  theme-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Theme Standards Check
        uses: imjafran/wpcs@v1.0.1
        with:
          standards: 'WordPress-Core,WordPress-Extra'
          ignore-patterns: 'node_modules/*,build/*,dist/*,assets/*'
          fail-on: 'warning'